/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeAssembly_64 */

#ifndef _Included_NativeAssembly_64
#define _Included_NativeAssembly_64
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeAssembly_64
 * Method:    print_eip
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeAssembly_164_print_1eip
  (JNIEnv *, jobject);

/*
 * Class:     NativeAssembly_64
 * Method:    print_rax
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeAssembly_164_print_1rax
  (JNIEnv *, jobject);

/*
 * Class:     NativeAssembly_64
 * Method:    print_rbx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeAssembly_164_print_1rbx
  (JNIEnv *, jobject);

/*
 * Class:     NativeAssembly_64
 * Method:    print_rcx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeAssembly_164_print_1rcx
  (JNIEnv *, jobject);

/*
 * Class:     NativeAssembly_64
 * Method:    print_rdx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeAssembly_164_print_1rdx
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
